language: bash
sudo: required
dist: trusty
env:
- PATH=$TRAVIS_BUILD_DIR/bin:$PATH
install: (sudo apt-get update || true) && bin/manage-tools -s setup
script: VIRTUALENVWRAPPER_SCRIPT=/usr/share/virtualenvwrapper/virtualenvwrapper.sh manage-tools -s test capstone
