language: bash
sudo: required
dist: xenial
env:
- PATH=$TRAVIS_BUILD_DIR/bin:$PATH
install: (sudo apt-get update || true) && bin/manage-tools -s setup
script: WORKON_HOME="$HOME/.virtualenvs" manage-tools -s test capstone
